#Push to main
#zip artifact has passed tests in the production org and code review in the pull request

#WARNING: this workflow will run automatically on pull request/merge approval. Be sure to approve the pull request on the proper release date.
#Deploy artifact to production org

#Previous step: pr-staging-to-main
#Next step: none

# Unique name for this workflow
name: Push/Org Deploy - main

#Pull request closed merge=true allows access to the ref branch while push does not
on:
  pull_request:
    types:
      - closed
    branches:
      - "main"
      - "Main"
      - "master"
      - "Master"
      - "prod"
      - "Prod"
      - "production"
      - "Production"

# Jobs to be executed
jobs:
  production-org-test-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      # Checkout the code in the pull request
      - name: "Checkout source code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
          sudo mkdir ~/sfdx-cli
          sudo tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx-cli --strip-components 1
          export PATH=$PATH:~/sfdx-cli/bin
          echo "~/sfdx-cli/bin" >> $GITHUB_PATH
          sudo chmod -R 777 ~/sfdx-cli
          sfdx --version

      # Store secret for dev hub org
      - name: "Populate auth file with PROD_SFDX_URL secret"
        run: "echo ${{secrets.PROD_SFDX_URL}} > ./PROD_SFDX_URL.txt"

      # Authenticate dev hub
      # Authorizes org using SFDX auth url stored in a file
      - name: "Authenticate Dev Hub"
        run: sfdx auth:sfdxurl:store -f ./PROD_SFDX_URL.txt -a devhub -d

      # Remove auth file
      - name: "Remove auth file"
        run: rm -f ./PROD_SFDX_URL.txt

      # Set config username for CLI Commands
      - name: "Set config username for CLI commands"
        run: sfdx config:set defaultusername=${{secrets.PROD_SFDX_USER}} defaultdevhubusername=${{secrets.PROD_SFDX_USER}}

      # Create/deploy release artifact to production org

      # Set build name from data for release artifact
      - name: Get date for build name
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Test with environment variables
        run: echo $RELEASE_NAME
        env:
          RELEASE_NAME: release-artifact-${{ steps.date.outputs.date }}

      # Store branch ids for reference
      - name: Get branch refs
        run: |
          echo "HEAD_REF=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV
          echo "BASE_REF=$(echo ${GITHUB_BASE_REF} | tr / -)" >> $GITHUB_ENV

      # Install SFDX & SFDX Git Delta
      - name: Install SFDX Git Delta
        run: |
          echo y | ~/sfdx-cli/bin/run plugins:install sfdx-git-delta
          git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
          git fetch --all
          git --no-pager diff --name-status origin/${{ env.BASE_REF }}^ origin/${{ env.HEAD_REF }}

      # Convert source code to metadata
      - name: Convert source code to metadata format
        run: sfdx force:source:convert --rootdir force-app --outputdir source_convert

      # Generate manifest
      - name: Generate destructive changes metadeta
        run: |
          sfdx sgd:source:delta --to origin/${{ env.HEAD_REF }} --from origin/${{ env.BASE_REF }}^ --output .
          echo
          echo "--- package.xml generated with added and modified metadata ---"
          cat package/package.xml
          echo
          echo
          echo
          echo "-- destructiveChanges.xml ---"
          cat destructiveChanges/destructiveChanges.xml
          echo
          echo
          echo
          echo "--- destructiveChanges/package.xml ---"
          cat destructiveChanges/package.xml

      # Copy changes to release artifact
      - name: Append destructive changes to source metadata
        run: cp destructiveChanges/destructiveChanges.xml source_convert

      # Create release artifact
      - name: Create release artifact
        run: zip -r release-artifact-${{steps.date.outputs.date}}.zip source_convert

      - name: Remove source convert output directory
        run: rm -r source_convert

      # Validate and deploy
      - name: Deploy artifact to production org
        run: sfdx force:mdapi:deploy --zipfile release-artifact-${{steps.date.outputs.date}}.zip --testlevel RunAllTestsInOrg -w 10
